[build]
    functions = "functions"
    publish = "public"

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"